### ISSUE TITLE
Reorganize files/folders

### ISSUE THREAD

**Issue by balazsorban44** [nhi/portable-text-dotnet#7]
For better readability and discoverability, I propose the following changes:

- [ ] Move the main [README.md](https://github.com/nhi/NHI.PortableText.DotNet/blob/master/README.md) under `NHI.PortableText` Where it belongs.
- [ ] Create an overview `README.md` that talks about the repository and its elements rather than only the parser (we not only have a NuGet package, but tests that are run against it, a .NET backend using that package and exposing the parser as a REST API, and a React front-end as an example to experiment with the results. We should name all these in the main README.md.)
- [ ] create three additional `README.md` files in `NHI.PortableText.Example`, `server` and `frontend` folders 
- [ ] Clarify the purpose of the [NuGet](https://github.com/nhi/NHI.PortableText.DotNet/tree/master/NuGet) directory. Is it necessary to have it in source control, can we move it under NHI.PortableText, etc.
- [ ] rename the folders for readability

So the proposed structure would be:
```
  |_ src (prev. /NHI.PortableText)
     |_NHI.PortableText (either a folder should be created with the source code, or the source code could live directly under `/src`)
     |_tests (prev. /NHI.PortableText.Test)
     |_NuGet(prev. /NuGet)
     |_README.md
  |_example (prev /NHI.PortableText.Example)
     |_frontend (prev. /NHI.PortableText.Example/frontend)
        |_README.md
     |_backend (prev. /NHI.PortableText.Example/server)
        |_README.md
     |_README.md
  |_README.md
```

**Comment by PetterRein** [comment]
I agree to move parts of the main readme into the folder `NHI.PortableText`, specific everything down of and including `Configuration`. The main purpose of this repo is the code/package to convert HTML to PortableText and it should be easy to understand from the main readme.

Then the main readme will now be so long and we can add the overviwe you propose.

The rest I agree to :-)

The NuGet folder is no longer needed now that the GitHub action publish the package for us
