### ISSUE TITLE
Add custom parser examples

### ISSUE THREAD

**Issue by balazsorban44** [nhi/portable-text-dotnet#8]
We should add some custom parsers to the online example both in `server` (either under the same endpoint or a different one) and `frontend`, while keeping the `frontend` as simple as possible.

**Comment by illiahonchar** [comment]
can you add me, its interesting for me

**Comment by balazsorban44** [comment]
@illiahonchar please feel free to clone the repo and tinker around, and open a PR for review! 🙂
