### ISSUE TITLE
Can we drop the NHI namespace from the NuGet package?

### ISSUE THREAD

**Issue by balazsorban44** [nhi/portable-text-dotnet#9]
I believe it is unnecessary to use the NHI namespace here.
https://www.nuget.org/packages/NHI.PortableText/

Can we drop NHI, since it is not an internal package anymore.

**Comment by PetterRein** [comment]
Probaly, but I dont know the side effects of renaming an already published package on NuGet.org

**Comment by balazsorban44** [comment]
Simply publish it under a different name, and publish a patch on NHI.PortableText saying it is deprecated and should use the other one. We should do it as quick as possible, in case general interest for the package grows rapidly (already around 50 downloads 🤓)

**Comment by balazsorban44** [comment]
#12 showed that we probably need it
